### ISSUE TITLE
discord.Bot.sync_commands not working as intended

### ISSUE THREAD

**Issue by aadhavksuresh** [Pycord-Development/pycord#911] opened 2022-02-04 04:00 UTC
### Summary

bot.sync_commands() doesn't register newer commands and produces an error when within cogs

### Reproduction Steps

1. Create a minimal bot and run a minimal version of the slash commands code (without cogs).
2. Now create a cog and run the cogs version of the minimal version of the slash commands code.

### Minimal Reproducible Code

```python
from discord.commands import slash_command
from discord.ext import commands


class Example(commands.Cog):

    def __init__(self, bot): 
        self.bot = bot

    @commands.Cog.listener()
    async def on_connect(self):
        print(self.bot.pending_application_commands)
        await self.bot.sync_commands()

    @slash_command(guild_ids=[...])
    async def ping(self, ctx):
        await ctx.respond(f"Pong! Websocket Latency = ``{round(self.bot.latency, 4) * 1000} ms``.")

def setup(bot):
    bot.add_cog(Example(bot))
```

### Expected Results

Slash Commands within the Cog works as expected and does not produce an error.

### Actual Results

``bot.sync_commands()`` produces the following error and the Slash Command within the cog doesn't work:

```Ignoring exception in on_connect
Traceback (most recent call last):
  File "/home/sirromey/discord_bots/test_ticket/ticket_bot/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/sirromey/discord_bots/test_ticket/ticket_bot/lib/python3.8/site-packages/discord/bot.py", line 1038, in on_connect
    await self.sync_commands()
  File "/home/sirromey/discord_bots/test_ticket/ticket_bot/lib/python3.8/site-packages/discord/bot.py", line 540, in sync_commands
    registered_commands = await self.register_commands(commands, force=force)
  File "/home/sirromey/discord_bots/test_ticket/ticket_bot/lib/python3.8/site-packages/discord/bot.py", line 382, in register_commands
    commands = copy.deepcopy(commands)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_asyncio.Task' object
```

### Intents

discord.Intents.all()

### System Information

```- Python v3.8.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b3
- aiohttp v3.8.1
- system info: Linux 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment] 2022-02-04 05:29
Fixed by 2b8f6d3e0abfe778f43900326f315a2c974f5145

**Closed by BobDotCom** 2022-02-04 05:29 UTC
Labels: bug

**Comment by Revnoplex** [comment] 2022-02-04 10:35
i get this same error using cogs

**Comment by Revnoplex** [comment] 2022-02-04 10:45
i tried using the fix but i got more errors:
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 1040, in on_connect
    await self.sync_commands()
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands
    registered_guild_commands[guild_id] = await self.register_commands(
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 419, in register_commands
    desynced = await self.get_desynced_commands(guild_id=guild_id)
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 285, in get_desynced_commands
    cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]]
KeyError: 'options'
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/bot-dir/cogs/Startup.py", line 31, in on_connect
    await self.client.sync_commands()
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands
    registered_guild_commands[guild_id] = await self.register_commands(
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 419, in register_commands
    desynced = await self.get_desynced_commands(guild_id=guild_id)
  File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 285, in get_desynced_commands
    cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]]
KeyError: 'options'

**Comment by BobDotCom** [comment] 2022-02-04 16:26
> i tried using the fix but i got more errors: Ignoring exception in on_connect Traceback (most recent call last): File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event await coro(*args, **kwargs) File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 1040, in on_connect await self.sync_commands() File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands registered_guild_commands[guild_id] = await self.register_commands( File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 419, in register_commands desynced = await self.get_desynced_commands(guild_id=guild_id) File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 285, in get_desynced_commands cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]] KeyError: 'options' Ignoring exception in on_connect Traceback (most recent call last): File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event await coro(*args, **kwargs) File "/bot-dir/cogs/Startup.py", line 31, in on_connect await self.client.sync_commands() File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands registered_guild_commands[guild_id] = await self.register_commands( File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 419, in register_commands desynced = await self.get_desynced_commands(guild_id=guild_id) File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 285, in get_desynced_commands cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]] KeyError: 'options'

Duplicate of #912
