### ISSUE TITLE
Strange library error when using some slash commands

### ISSUE THREAD

**Issue by randomairborne** [Pycord-Development/pycord#170] opened 2021-09-11 04:04 UTC
### Summary

Random error with slash commands

### Reproduction Steps

ran https://github.com/GlaceonBot/Sylveon with default settings
Tried to run /hug
Noted error

### Minimal Reproducible Code

```python
see https://github.com/GlaceonBot/Sylveon/blob/master/bot.py#L78 to line 99
```

### Expected Results

I expected the command to complete correctly, as there don't seem to be issues with the bot code

### Actual Results

Nothing, the command failed and i got a traceback
```
Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/Glaceon/Sylveon/venv/lib/python3.9/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "/home/Glaceon/Sylveon/venv/lib/python3.9/site-packages/discord/bot.py", line 373, in on_interaction
    await self.handle_interaction(interaction)
  File "/home/Glaceon/Sylveon/venv/lib/python3.9/site-packages/discord/bot.py", line 248, in handle_interaction
    await command.invoke(context)
  File "/home/Glaceon/Sylveon/venv/lib/python3.9/site-packages/discord/app/commands.py", line 154, in invoke
    arg = await get_or_fetch(ctx.guild, name, int(arg))
  File "/home/Glaceon/Sylveon/venv/lib/python3.9/site-packages/discord/utils.py", line 453, in get_or_fetch
    getter = getattr(obj, f'get_{attr}')(id)
AttributeError: 'NoneType' object has no attribute 'get_member'
```

### Intents

discord.Intents.none()

### System Information

- Python v3.9.2-final
- pycord v2.0.0-alpha
    - pycord pkg_resources: v2.0.0a3840+ge6226504
- aiohttp v3.7.4.post0
- system info: Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Sometimes this is fixed by restarting the bot, but then a few hours later it crops up on a different command.

**Comment by nerdguyahmad** [comment] 2021-09-11 04:32
Did you run the command in a DM channel?

**Comment by randomairborne** [comment] 2021-09-12 02:02
No, this is in a normal channel

**Comment by Makiyu-py** [comment] 2022-01-14 07:56
Cannot reproduce anymore, closing

**Closed by Makiyu-py** 2022-01-14 07:56 UTC
Labels: unconfirmed bug
