### ISSUE TITLE
Bug with command groups

### ISSUE THREAD

**Issue by Vondyy** [Pycord-Development/pycord#1593] opened 2022-08-26 01:48 UTC
### Summary

Command groups doesnt work

### Reproduction Steps

update to Update to pip install -U py-cord==2.1.1

downgrading to pip install -U py-cord==2.0.1
 fixes it

### Minimal Reproducible Code

```python
random2 = CLIENT.create_group("random", "Random commands.")  # create a slash command group

@random2.command(description="Sup")
async def sup(ctx):
    await ctx.respond(f"{ctx.author.mention} Sup")
```

### Expected Results

For the command to work and not given error

### Actual Results

command give a long ass error

The application did not respond

Ignoring exception in on_interaction
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1202, in _invoke
    await command.invoke(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 356, in invoke
    await self.prepare(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 278, in prepare
    if not await self.can_run(ctx):
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 373, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 997, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 359, in invoke
    await injected(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 1046, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 741, in process_application_commands
    await self.invoke_application_command(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 1001, in invoke_application_command
    await ctx.command.dispatch_error(ctx, exc)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 401, in dispatch_error
    local = cog.__class__._get_overridden_method(cog.cog_command_error)
AttributeError: type object '_MissingSentinel' has no attribute '_get_overridden_method'
Ignoring exception in command random sup:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 127, in wrapped
    ret = await coro(arg)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1202, in _invoke
    await command.invoke(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 356, in invoke
    await self.prepare(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 278, in prepare
    if not await self.can_run(ctx):
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 373, in can_run
    local_check = cog._get_overridden_method(cog.cog_check)
AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 997, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 359, in invoke
    await injected(ctx)
  File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 135, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'

### Intents

intents.message_content = True

### System Information

/usr/bin/python3: No module named discord
 but im using pterodactyl to host the bot on my vps. So,I think that's why it gives me that error cause all the normal slash commands work fine.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

downgrading to previous versions fixes the bug.

**Comment by yoggys** [comment] 2022-08-26 09:55
can you show more code? can't reproduce this

**Comment by Vondyy** [comment] 2022-08-27 01:01
import discord

bot = discord.Bot() # specify the guild IDs in debug_guilds

# create slash command group with bot.create_group
greetings = bot.create_group("greetings", "Greet people")

@greetings.command()
async def hello(ctx):
  await ctx.respond(f"Hello, {ctx.author}!")

@greetings.command()
async def bye(ctx):
  await ctx.respond(f"Bye, {ctx.author}!")




bot.run('my token here')


version py-cord==2.1.1

**Comment by emhl** [comment] 2022-08-27 13:33
i'm currently having the same issue

**Comment by yoggys** [comment] 2022-08-27 14:21
no problems for me on latest versions
@Vondyy could you run `python3 -m discord -v` or `python -m discord -v` because there are no system snformations

**Comment by Vondyy** [comment] 2022-08-28 01:10
alexm@vps:~$ python3 -m discord -v
/usr/bin/python3: No module named discord
alexm@vps:~$ python -m discord -v

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python' from deb python-is-python3

as i said before I'm running this on pterodactyl which is in a docker container I guess, so I'm assuming this is why I'm being shown discord isn't found

**Comment by Vlad2530** [comment] 2022-08-28 04:13
> ### Summary
> Command groups doesnt work
> 
> ### Reproduction Steps
> update to Update to pip install -U py-cord==2.1.1
> 
> downgrading to pip install -U py-cord==2.0.1 fixes it
> 
> ### Minimal Reproducible Code
> ```python
> random2 = CLIENT.create_group("random", "Random commands.")  # create a slash command group
> 
> @random2.command(description="Sup")
> async def sup(ctx):
>     await ctx.respond(f"{ctx.author.mention} Sup")
> ```
> 
> ### Expected Results
> For the command to work and not given error
> 
> ### Actual Results
> command give a long ass error
> 
> The application did not respond
> 
> Ignoring exception in on_interaction Traceback (most recent call last): File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 127, in wrapped ret = await coro(arg) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1202, in _invoke await command.invoke(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 356, in invoke await self.prepare(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 278, in prepare if not await self.can_run(ctx): File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 373, in can_run local_check = cog._get_overridden_method(cog.cog_check) AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'
> 
> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 997, in invoke_application_command await ctx.command.invoke(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 359, in invoke await injected(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 135, in wrapped raise ApplicationCommandInvokeError(exc) from exc discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'
> 
> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/container/.local/lib/python3.10/site-packages/discord/client.py", line 382, in _run_event await coro(*args, **kwargs) File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 1046, in on_interaction await self.process_application_commands(interaction) File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 741, in process_application_commands await self.invoke_application_command(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 1001, in invoke_application_command await ctx.command.dispatch_error(ctx, exc) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 401, in dispatch_error local = cog.**class**._get_overridden_method(cog.cog_command_error) AttributeError: type object '_MissingSentinel' has no attribute '_get_overridden_method' Ignoring exception in command random sup: Traceback (most recent call last): File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 127, in wrapped ret = await coro(arg) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 1202, in _invoke await command.invoke(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 356, in invoke await self.prepare(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 278, in prepare if not await self.can_run(ctx): File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 373, in can_run local_check = cog._get_overridden_method(cog.cog_check) AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'
> 
> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/home/container/.local/lib/python3.10/site-packages/discord/bot.py", line 997, in invoke_application_command await ctx.command.invoke(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 359, in invoke await injected(ctx) File "/home/container/.local/lib/python3.10/site-packages/discord/commands/core.py", line 135, in wrapped raise ApplicationCommandInvokeError(exc) from exc discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: '_MissingSentinel' object has no attribute '_get_overridden_method'
> 
> ### Intents
> intents.message_content = True
> 
> ### System Information
> /usr/bin/python3: No module named discord but im using pterodactyl to host the bot on my vps. So,I think that's why it gives me that error cause all the normal slash commands work fine.
> 
> ### Checklist
> * [x]  I have searched the open issues for duplicates.
> * [x]  I have shown the entire traceback, if possible.
> * [x]  I have removed my token from display, if visible.
> 
> ### Additional Context
> downgrading to previous versions fixes the bug.

I'm facing the same problem

**Comment by plun1331** [comment] 2022-08-28 05:46
Should be fixed in #1594

**Closed by plun1331** 2022-08-28 05:46 UTC
Labels: bug

**Comment by Vondyy** [comment] 2022-08-28 14:16
When will this be pushed to pip? Feel like this is a pretty big bug

**Comment by Lulalaby** [comment] 2022-08-28 15:15
> When will this be pushed to pip? Feel like this is a pretty big bug

You can't read, can you?

**Comment by Vondyy** [comment] 2022-08-28 19:26
Saying it's completeted isn't saying it's pushed to pip dumb fuck. No need to be rude.

**Comment by Vondyy** [comment] 2022-08-28 19:29
They just said it was fixed that's all
