### ISSUE TITLE
Add the ability to set a custom_view for each page of a paginator

### ISSUE THREAD

**Issue by Ahsoka** [Pycord-Development/pycord#1086] opened 2022-02-27 04:32 UTC
### Summary

I would like to be able to set a `custom_view` for each page of a paginator.  See the following example for reference:

![Custom View for Each Page of Paginator](https://user-images.githubusercontent.com/34612646/155868402-25cb0e22-900f-490e-b297-d4df8ab267f7.gif)

### What is the feature request for?

discord.ext.pages

### The Problem

Like mentioned above I would like to be able to use a `custom_view` for each page in a paginator.

### The Ideal Solution

There are two implementations I can think of.

1. You can enable users to pass the following type of structure to the `pages` parameter:
    ```py
    Sequence[
        Tuple[
            Union[str, discord.Embed, Sequence[discord.Embed]],
            discord.ui.View
         ]
    ]
    ```
2. You can create a new class to hold the information mentioned above like is done with the `PageGroup` class to create different page groups and allow users to pass that class or list of classes as an acceptable parameter.

### The Current Solution

None, other than inheriting the `Paginator` class and writing custom code, like I did [here](https://github.com/Ahsoka/clovis/blob/71ac860ccfe2d9b80868218336f76b6b5ea7f65b/clovis/utils.py#L178-L202).

**Comment by krittick** [comment] 2022-04-03 21:14
Closing as this is a duplicate of #955

**Closed by krittick** 2022-04-03 21:14 UTC
Labels: feature request, priority: medium, status: in progress, pages
