### ISSUE TITLE
sync_commands() is broken

### ISSUE THREAD

**Issue by Revnoplex** [Pycord-Development/pycord#922] opened 2022-02-04 12:09 UTC
### Summary

when upgrading to the latest mater branch after attempting to fix another bug with sync_commands() from 2.0.0b3, another bug occured

### Reproduction Steps

a bot with slash commands in cogs
not sure what else

### Minimal Reproducible Code

```python
async def on_connect():
   client.sync_commands()
```

### Expected Results

to load the commands correctly

### Actual Results

Ignoring exception in on_connect
Traceback (most recent call last):
File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
await coro(*args, **kwargs)
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 1040, in on_connect
await self.sync_commands()
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands
registered_guild_commands[guild_id] = await self.register_commands(
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 419, in register_commands
desynced = await self.get_desynced_commands(guild_id=guild_id)
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 285, in get_desynced_commands
cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]]
KeyError: 'options'
Ignoring exception in on_connect
Traceback (most recent call last):
File "/bot-dir/venv/lib/python3.10/site-packages/discord/client.py", line 352, in _run_event
await coro(*args, **kwargs)
File "/bot-dir/cogs/Startup.py", line 31, in on_connect
await self.client.sync_commands()
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 552, in sync_commands
registered_guild_commands[guild_id] = await self.register_commands(
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 419, in register_commands
desynced = await self.get_desynced_commands(guild_id=guild_id)
File "/bot-dir/venv/lib/python3.10/site-packages/discord/bot.py", line 285, in get_desynced_commands
cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]]
KeyError: 'options

### Intents

defaults, members, guilds, messages 

### System Information

python 3.10.1 (venv)
ubuntu 20.04
pycord master

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I don't have access to the machine with the bot code rn so i can't provide much. but I can provide more in a few hours

**Comment by BobDotCom** [comment] 2022-02-04 13:37
Duplicate of #912

**Closed by BobDotCom** 2022-02-04 13:37 UTC
Labels: unconfirmed bug
