### ISSUE TITLE
Can't fetch vanity url

### ISSUE THREAD

**Issue by Miolus** [Pycord-Development/pycord#797] opened 2022-01-15 09:24 UTC
### Summary

PyCord's alpha raised an error when trying to fetch the vanity_url.

### Reproduction Steps

Try to fetch the vanity invite from a guild.

### Minimal Reproducible Code

```python
invite = await member.guild.vanity_invite()
```

### Expected Results

return `discord.Invite` object.

### Actual Results

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/root/invitechecker/shard/engine/memberevents.py", line 70, in on_member_join
    invite = await member.guild.vanity_invite()
  File "/usr/local/lib/python3.9/dist-packages/discord/guild.py", line 2749, in vanity_invite
    data = await self._state.http.get_invite(payload['code'])
  File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 1450, in get_invite
    'guild_scheduled_event_id': int(guild_scheduled_event_id),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### Intents

discord.Intents.member

### System Information

python3.9

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment] 2022-01-15 09:39
Cannot reproduce. Is your pycord on the latest commit?

**Comment by plun1331** [comment] 2022-01-15 10:33
This should have been fixed in #694

**Closed** 2022-01-15 10:38 UTC
Labels: unconfirmed bug
