### ISSUE TITLE
Disabling Slash Commands For Certain Guilds Or Users

### ISSUE THREAD

**Issue by AmirAvram** [Pycord-Development/pycord#247] opened 2021-10-03 11:45 UTC
### Summary

Disabling slash commands using already builtin boolean

### What is the feature request for?

discord.ext.commands

### The Problem

Currently there is no real way to "truly" hide admin commands from the bot, but there is a way to disable them.
While trying to find a solution to the problem above, I've stumbled upon the next [PR](https://github.com/discord/discord-api-docs/pull/2737/files) in discord-api-docs git, which allows to disable commands to specific guild roles or user-ids.

I've tested if the disabling indeed works by adding `"default_permission": False,` to the registration of a new slash command, and saw this in discord:
![image](https://user-images.githubusercontent.com/7930622/135751975-794297d8-36c3-4bc1-9cbd-5e8a11711c6c.png)

As you can see the command is indeed disabled.

### The Ideal Solution

I think the ideal solution would be allowing another parameter/class to be passed trough the slash_command decorator (like guild_ids) which will in turn construct the permission json and pass it trough to the Discord gateway.

### The Current Solution

There is none

### Additional Context

I'll be more then happy to try and open a PR for that with a little bit of guidance.

**Comment by nerdguyahmad** [comment] 2021-10-03 12:35
This can be potential dupe of #93 but it was closed so, FYI, These are application commands permissions.

**Closed** 2021-10-30 02:06 UTC
Labels: feature request

**Comment by DamiansNase** [comment] 2024-02-16 11:40
Wen definitely need this

**Comment by Lulalaby** [comment] 2024-02-16 15:08
@DamiansNase this does not exist anymore due to discord switching to another system for it.
Please inform yourself next time earlier instead of commenting to an ~2 years old issue.
