### ISSUE TITLE
Attachment option fails in subcommands

### ISSUE THREAD

**Issue by Middledot** [Pycord-Development/pycord#1004] opened 2022-02-13 03:00 UTC
### Summary

Using attachment options in subcommands breaks

### Reproduction Steps

What I have that caused it
```py
# slash_js_card is a subcommand group of another command
@slash_js_card.command(name="background")
async def slash_js_card_bg(
    self,
    ctx,
    image: discord.Option(
        discord.Attachment,
        default = None,
        required = False
    )
):
    # stuff
```

### Minimal Reproducible Code

```python
import discord

bot = discord.Bot()

cmd = bot.create_group("cmd", "a group")
sub = cmd.create_subgroup("sub", "another sub")

@sub.command(name="subest")
async def cmd_sub_subest(ctx, image: discord.Option(discord.Attachment, description="Your image")):
    await ctx.respond(image.url)

bot.run("token")
```

### Expected Results

The bot to send the image url

### Actual Results

Errors out with this:
```py
Ignoring exception in command cmd sub subest:
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 766, in _invoke
    _data = ctx.interaction.data["resolved"]["attachments"][arg]
KeyError: 'resolved'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\bot.py", line 770, in process_application_commands
    await ctx.command.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 308, in invoke
    await injected(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 1036, in _invoke
    await command.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 308, in invoke
    await injected(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 110, in wrapped
    ret = await coro(arg)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 1036, in _invoke
    await command.invoke(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 308, in invoke
    await injected(ctx)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\commands\core.py", line 116, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: 'resolved'
```
This is what "interaction.data" shows:
```
{'type': 1, 'options': [{'value': '942250275891195904', 'type': 11, 'name': 'image'}], 'name': 'subest'}
```

### Intents

Basically all of them except typing

### System Information

```
- Python v3.9.0-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

After some debugging this seems to be related to how subcommands are processed:
```
(cmd) SOME DATA:  {'type': 1, 'resolved': {'attachments': {'942250275891195904': {'width': 2048, 'url': 'https://cdn.discordapp.com/ephemeral-attachments/942250182811209738/942250275891195904/imisstensecondsago.jpg', 'size': 221367, 'proxy_url': 'https://media.discordapp.net/ephemeral-attachments/942250182811209738/942250275891195904/imisstensecondsago.jpg', 'id': '942250275891195904', 'height': 1152, 'filename': 'imisstensecondsago.jpg', 'ephemeral': True, 'content_type': 'image/jpeg'}}}, 'options': [{'type': 2, 'options': [{'type': 1, 'options': [{'value': '942250275891195904', 'type': 11, 'name': 'image'}], 'name': 'subest'}], 'name': 'sub'}], 'name': 'cmd', 'id': '942250182811209738'}
cmd
---------------------------------------------------------------------------
(sub) SOME DATA:  {'type': 2, 'options': [{'type': 1, 'options': [{'value': '942250275891195904', 'type': 11, 'name': 'image'}], 'name': 'subest'}], 'name': 'sub'}
sub
---------------------------------------------------------------------------
(subest) SOME DATA:  {'type': 1, 'options': [{'value': '942250275891195904', 'type': 11, 'name': 'image'}], 'name': 'subest'}
subest
```
I put this code in `ApplicationCommand.invoke` to get the above
```py
async def invoke(self, ctx: ApplicationContext) -> None:
    await self.prepare(ctx)
    print(f"({ctx.command.name}) SOME DATA: ", ctx.interaction.data)
    print(self.name)
    print("---------------------------------------------------------------------------")
    injected = hooked_wrapped_callback(self, ctx, self._invoke)
    await injected(ctx)
```

**Comment by plun1331** [comment] 2022-02-13 06:17
Duplicate of #982

**Closed** 2022-02-13 14:06 UTC
Labels: unconfirmed bug
