### ISSUE TITLE
Error when invoking a slash command function that has a channel as the option type

### ISSUE THREAD

**Issue by bavalpey** [Pycord-Development/pycord#1279] opened 2022-04-19 16:04 UTC
### Summary

Slash commands that use channel cannot be invoked without error

### Reproduction Steps

Create a slash command that takes in a SlashCommandOptionType.channel, and then invoke it.

### Minimal Reproducible Code

```python
e.g.

@slash_command
async def say(self, ctx: ApplicationContext,
              to_channel: Option(SlashCommandOptionType.channel, 
                                 description="which channel",
                                 channel_types=[ChannelType.text],
                                 required=True)
    await to_channel.send("Hello World!")
```

### Expected Results

The command should send the message without any error after being invoked.

### Actual Results

The command fails, stating `discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: 'tuple' object is not callable`

Entire traceback:

```
Traceback (most recent call last):
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 122, in wrapped
    ret = await coro(arg)
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 858, in _invoke
    arg = obj_type(state=ctx.interaction._state, data=_data, **kw)
TypeError: 'tuple' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/bot.py", line 1098, in invoke_application_command
    await ctx.command.invoke(ctx)
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 345, in invoke
    await injected(ctx)
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 122, in wrapped
    ret = await coro(arg)
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 1155, in _invoke
    await command.invoke(ctx)
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 345, in invoke
    await injected(ctx)
  File "/home/bavalpey/projects/FoF-bot/.venv/lib/python3.10/site-packages/discord/commands/core.py", line 128, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: 'tuple' object is not callable
```

### Intents

all

### System Information

2.0.0b7

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This bug is due to the `_guild_channel_factory` function in `channel.py` (line 2200) returning a Tuple.  It can be fixed by changing line 806 in `core.py` to `obj_type, _ = _guild_channel_factory(_data["type"])`

**Comment by plun1331** [comment] 2022-04-19 22:45
This was already fixed in https://github.com/Pycord-Development/pycord/commit/9fdfd56cb7f73daf98b5013a9fd231665746dd0b, you should update to the GitHub version.

**Comment by cannonballchris** [comment] 2022-04-20 11:55
I am facing the same error, and I wish the update to be released soon in pypi as I don't use github versions of libraries

**Comment by INTJax** [comment] 2022-04-24 10:38
I have also experienced this issue on 2.0.0-beta.7
The issue is not present in 2.0.0-beta.5

I raised it in the py-cord Discord server
https://discord.com/channels/881207955029110855/881309521610412082/967728796818100295

**Comment by Snawe** [comment] 2022-05-03 17:07
Yes. Can confirm that with current master (44eb9a0).

**Comment by Fallcrim** [comment] 2022-05-08 14:44
Running into the same issue in 2.0.0b7

**Comment by Dorukyum** [comment] 2022-05-13 13:40
I cannot reproduce this with the given code.

**Comment by Snawe** [comment] 2022-05-18 04:46
Can confirm. With `2.0.0rc1` it works again

**Closed** 2022-05-18 21:16 UTC
Labels: unconfirmed bug
