### ISSUE TITLE
Slash commands in cog doesn't load

### ISSUE THREAD

**Issue by Hype3808** [Pycord-Development/pycord#345] opened 2021-10-29 02:36 UTC
### Summary

Slash commands in cog doesn't load

### Reproduction Steps

Loading Slash Cogs

### Minimal Reproducible Code

```python
Ignoring exception in on_connect
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 555, in on_connect
    await self.register_commands()
  File "/home/container/.local/lib/python3.8/site-packages/discord/bot.py", line 197, in register_commands
    global_permissions.append({"id": i["id"], "permissions": cmd.permissions})
AttributeError: 'NoneType' object has no attribute 'permissions'
```

### Expected Results

The slash commands are working

### Actual Results

The slash commands doesn't load

### Intents

all

### System Information

Python 3.7.3
py-cord 2.0.0a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment] 2021-10-29 19:31
duplicate of #342.

**Closed by BobDotCom** 2021-10-29 19:31 UTC
Labels: unconfirmed bug
