### ISSUE TITLE
ScheduledEvent image is called 'image' on creation, but 'cover' on edit

### ISSUE THREAD

**Issue by honzajavorek** [Pycord-Development/pycord#2161] opened 2023-07-03 16:09 UTC
### Summary

Such naming is inconsistent and counter-intuitive. Perhaps not a bug, feel free to close as wontfix.

### Reproduction Steps

Compare signatures of the following functions:

- https://docs.pycord.dev/en/stable/api/models.html#discord.Guild.create_scheduled_event
- https://docs.pycord.dev/en/stable/api/models.html#discord.ScheduledEvent.edit

### Expected Results

The parameters have the same name as in practice they're the same thing.

### Actual Results

The parameters have different names, which is confusing.

### Intents

standard ones

### System Information

irrelevant?

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment] 2023-11-30 15:36
Duplicate of #2010.

**Closed** 2023-11-30 15:37 UTC
Labels: unconfirmed bug, on hold
