### ISSUE TITLE
Cog Unloading

### ISSUE THREAD

**Issue by EggsLeggs** [Pycord-Development/pycord#550] opened 2021-12-07 19:47 UTC
### Summary

When trying to unload a cog you get a key error

### Reproduction Steps

I seem to get this error regardless of what formatting I use to try and do to unload the cog

### Minimal Reproducible Code

```python
##--- Imports ---
import discord
from discord.commands import permissions, Option, slash_command
import glob

intents = discord.Intents.all()
bot = discord.Bot()

loaded_cogs = []

cogManagement = bot.command_group(
    "cog",
    "Commands related to cog management.",
    guild_ids=[guild id],
)

async def get_available_cogs(ctx: discord.AutocompleteContext):
    available_cogs = [file[5:-3] for file in glob.glob("cogs/*.py")]
    return [matching_cog for matching_cog in available_cogs if matching_cog.startswith(ctx.value.lower()) and matching_cog not in loaded_cogs]

async def get_loaded_cogs(ctx: discord.AutocompleteContext):
    return [matching_cog for matching_cog in loaded_cogs if matching_cog.startswith(ctx.value.lower())]

@cogManagement.command(name="load", description = 'N/A')
async def _loadcog(ctx: discord.ApplicationContext, cog: Option(str, "Select a Cog.", autocomplete=get_available_cogs, required=True)):
    bot.load_extension(f'cogs.{cog}')
    loaded_cogs.append(cog)

##-- Command To Unload Cogs Manually
@cogManagement.command(name="unload", description = 'N/A')
async def _unloadcog(ctx: discord.ApplicationContext, cog: Option(str, "Select a Cog.", autocomplete=get_loaded_cogs, required=True)):
    bot.unload_extension(f'cogs.{cog}')
    loaded_cogs.remove(cog)

bot.run('key')
```

### Expected Results

It should just unload the cog

### Actual Results

Ignoring exception in command <discord.commands.SlashCommand name=unload>:
Traceback (most recent call last):
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 85, in wrapped
    ret = await coro(arg)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 532, in _invoke
    await self.callback(ctx, **kwargs)
  File "d:\Documents (HD)\Discord\Bots\The Waffle Squad\GateKeeper Astro\Astro Code\core.py", line 44, in _unloadcog
    bot.unload_extension(f'cogs.{cog}')
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\cog.py", line 770, in unload_extension
    self._remove_module_references(lib.__name__)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\cog.py", line 616, in _remove_module_references
    self.remove_cog(cogname)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\cog.py", line 600, in remove_cog
    cog._eject(self)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\cog.py", line 484, in _eject
    bot.remove_application_command(command)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\bot.py", line 144, in remove_application_command
    return self._application_commands.pop(command.id)
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\bot.py", line 444, in process_application_commands
    await ctx.command.invoke(ctx)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 134, in invoke
    await injected(ctx)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 85, in wrapped
    ret = await coro(arg)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 799, in _invoke
    await command.invoke(ctx)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 134, in invoke
    await injected(ctx)
  File "C:\Users\haybr\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\commands\commands.py", line 91, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: KeyError: None

### Intents

discord.Intents.all

### System Information

- Python v3.8.7-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4501+g9fceff87
- aiohttp v3.7.3
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by rmenai** [comment] 2021-12-11 07:43
Isn't this a duplicate of #401? I had the same issue

**Comment by Lulalaby** [comment] 2021-12-23 20:39
Atm intended

**Closed by Lulalaby** 2021-12-23 20:39 UTC
Labels: unconfirmed bug
