### ISSUE TITLE
Import errors in cogs are ignored

### ISSUE THREAD

**Issue by tiltowait** [Pycord-Development/pycord#1547] opened 2022-08-05 23:58 UTC
### Summary

In 2.0.0, import errors in cogs are silently ignored.

### Reproduction Steps

Simply add a cog with an error in the code body: import a nonexistent file, omit the `setup()` function, etc.

### Minimal Reproducible Code

**main.py**
```python
import discord

bot = discord.Bot(intents=discord.Intents.default())
bot.load_extension("cog")

bot.run(<token>)
```

**cog.py**
```py
from discord.ext import commands

import nonexistent_package


class TestCog(commands.Cog):
    pass

def setup(bot):
    bot.add_cog(TestCog(bot))
```

### Expected Results

A `ModuleNotFoundError` should prevent the bot from starting.

### Actual Results

The bot runs without even printing an error message. This can cause slash commands in broken cogs from disappearing and can be difficult to diagnose if the error is in a package imported *by* the cog.

### Intents

default, but n/a

### System Information

- Python v3.10.5-final
- py-cord v2.0.0-final
- aiohttp v3.8.1
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This bug does not exist in 2.0.0rc1.

**Comment by plun1331** [comment] 2022-08-06 02:50
Dupe of #1502

**Comment by tiltowait** [comment] 2022-08-06 03:19
Interesting. The documentation suggests `store` defaults to `False`.

**Comment by baronkobama** [comment] 2022-08-06 03:42
> Interesting. The documentation suggests `store` defaults to `False`.

The documentation is correct, however, it is not reflecting 2.0.0, it's reflecting the GitHub master branch. If you were to move to GitHub master, you'd see that `store` now defaults to `False` instead of `True`. This will be put in 2.1.0 as setting `store` to `True` by default in 2.0.0 has created a bit too much confusion.

**Closed** 2022-09-23 00:55 UTC
Labels: unconfirmed bug

**Comment by Disuqi** [comment] 2023-08-22 19:16
I have the opposite thing happening to me, I get a ModuleNotFoundError for an existing file
