### ISSUE TITLE
AttributeError: 'PartialMessageable' object has no attribute 'permissions_for'

### ISSUE THREAD

**Issue by Asherlam** [Pycord-Development/pycord#497] opened 2021-11-24 09:04 UTC
### Summary

core bug

### Reproduction Steps

i didn't do anything, it random pop up this error.

### Minimal Reproducible Code

```python
(most recent call last):
  File "/home/container/.local/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/.local/lib/python3.9/site-packages/discord/bot.py", line 562, in on_interaction
    await self.process_application_commands(interaction)
  File "/home/container/.local/lib/python3.9/site-packages/discord/bot.py", line 384, in process_application_commands
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.9/site-packages/discord/commands/commands.py", line 130, in invoke
    await self.prepare(ctx)
  File "/home/container/.local/lib/python3.9/site-packages/discord/commands/commands.py", line 122, in prepare
    if not await self.can_run(ctx):
  File "/home/container/.local/lib/python3.9/site-packages/discord/commands/commands.py", line 145, in can_run
    return await async_all(predicate(ctx) for predicate in predicates) # type: ignore
  File "/home/container/.local/lib/python3.9/site-packages/discord/utils.py", line 538, in async_all
    for elem in gen:
  File "/home/container/.local/lib/python3.9/site-packages/discord/commands/commands.py", line 145, in <genexpr>
    return await async_all(predicate(ctx) for predicate in predicates) # type: ignore
  File "/home/container/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1987, in predicate
    permissions = ch.permissions_for(ctx.author)  # type: ignore
AttributeError: 'PartialMessageable' object has no attribute 'permissions_for'
```

### Expected Results

i don't expect any error

### Actual Results

please the fix the bug

### Intents

member

### System Information

Python version: 3.9.4
Pycord version: 2.0.0a

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by BobDotCom** [comment] 2021-11-29 16:45
I can't do anything with the information given, please provide *Minimal Reproducible Code* as was requested in the form.

**Comment by UP929312** [comment] 2021-12-06 19:20
I've had this before, it's more than likely that someone is using a slash command in a direct message

**Comment by EmreTech** [comment] 2022-01-09 00:22
@Asherlam you really need to give out reproducible code, NOT just the error you get from the Terminal.
If you don't respond to this within a certain time frame, then I think someone should close this invalid issue.

**Comment by timmypidashev** [comment] 2022-01-23 06:55
This is a user error, pretty sure its because the channel/dm the command was used doesn't have said attribute to begin with...

**Comment by plun1331** [comment] 2022-01-23 07:00
> This is a user error, pretty sure its because the channel/dm the command was used doesn't have said attribute to begin with...

This is not a user error, the traceback shows that it came from the  internals of the lib.

It's most likely an issue with not getting the channel properly, and as a result the command's permission checks have a stroke.

**Comment by GDKID69** [comment] 2022-01-23 15:52
This happens to me with one of my slash commands that can't be used in DMs, however its odd that none of my other guild-only ones get this error, I'm guessing it's because this particular one uses multiple check decorators (has_guild_permissions(), etc)

**Comment by dandesousa** [comment] 2022-02-10 01:19
I see this on all my slash commands when executing in the context of a DM. I see it with a command that looks like this. Global command works fine but fails in a DM, spits out the stack trace above (2.0.0-beta-1

```python
class ExampleCog(commands.Cog):
    def __init__(self, bot: discord.Client) -> None:
        self.bot = bot

    @commands.max_concurrency(1, per=commands.BucketType.member, wait=False)
    @commands.cooldown(rate=2, per=60, type=commands.BucketType.member)
    @slash_command()
    async def example(
        self,
        ctx: ApplicationContext,
      
    ) -> None:
        pass
```

Exception
```
...
"  File \"\/Users\/daniel\/venv\/pokenav-pycord\/lib\/python3.9\/site-packages\/discord\/ext\/commands\/core.py\", line 2022, in predicate\n    permissions = ctx.channel.permissions_for(me)  # type: ignore\n","AttributeError: 'PartialMessageable' object has no attribute 'permissions_for'\n"
```

**Comment by EmreTech** [comment] 2022-02-10 01:47
> I see this on all my slash commands when executing in the context of a DM. I see it with a command that looks like this. Global command works fine but fails in a DM, spits out the stack trace above (2.0.0-beta-1)
> 
> 
> 
> ```python
> 
> import discord
> 
> from discord.ext import commands  # type: ignore
> 
> from discord.commands import ApplicationContext, Option, slash_command
> 
> 
> 
> class ExampleCog(commands.Cog):
> 
>     def __init__(self, bot: discord.Client) -> None:
> 
>         self.bot = bot
> 
> 
> 
>     @commands.max_concurrency(1, per=commands.BucketType.member, wait=False)
> 
>     @commands.cooldown(rate=2, per=60, type=commands.BucketType.member)
> 
>     @slash_command()
> 
>     async def example(
> 
>         self,
> 
>         ctx: ApplicationContext,
> 
>       
> 
>     ) -> None:
> 
>         pass
> 
> ```
> 
> 
> 
> Exception
> 
> ```
> 
> ...
> 
> "  File \"\/Users\/daniel\/venv\/pokenav-pycord\/lib\/python3.9\/site-packages\/discord\/ext\/commands\/core.py\", line 2022, in predicate\n    permissions = ctx.channel.permissions_for(me)  # type: ignore\n","AttributeError: 'PartialMessageable' object has no attribute 'permissions_for'\n"
> 
> ```

FINALLY some reproducible code! We can now pinpoint the problem of this issue.

**Comment by timmypidashev** [comment] 2022-02-10 02:10
@plun1331 My apologies, you are correct it seems, a lib error.

**Comment by baronkobama** [comment] 2022-06-12 07:55
Unable to reproduce on either 2.0.0b1 or 2.0.0rc1, it appears this was either invalid from the start or fixed at some point. Close as stale/invalid?

**Closed** 2022-06-12 12:21 UTC
Labels: unconfirmed bug
