### ISSUE TITLE
guild.icon.url respond None

### ISSUE THREAD

**Issue by Areoxy** [Pycord-Development/pycord#726] opened 2022-01-07 19:27 UTC
### Summary

guild.icon.url respond None

### Reproduction Steps

i don't know if it a bug or rather a feature request  but
I wanted to get the guils icon url with guild.icon and if the guild havn't a icon it respond None.

### Minimal Reproducible Code

```python
...
embed.set_footer(icon_url=guild.icon.url)
await ctx.respond(embed=embed)
```

### Expected Results

That the bot respond a default icon or client icon.

### Actual Results

The bot raised a error:

```sh
embed.set_footer(icon_url=guild.icon.url)
AttributeError: 'NoneType' object has no attribute 'url'
```

### Intents

discord.Intents.all()

### System Information

Windows 11
Python 3.9.6
Newest Pyocrd alpha

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I think it would be nice if in such a case it would respond the client icon instead of None.

**Comment by PythonIntermediateCoder** [comment] 2022-01-08 02:32
It's not a bug, there's no default icon for guilds.

**Comment by Lulalaby** [comment] 2022-01-08 02:33
Closing as invalid

**Closed by Lulalaby** 2022-01-08 02:33 UTC
Labels: invalid
