### ISSUE TITLE
Disconnections Not Being Handled Correctly

### ISSUE THREAD

**Issue by KosmicAnomaly** [Pycord-Development/pycord#1098] opened 2022-02-28 15:17 UTC
### Summary

Pycord does not properly handle when a bot is manually disconnected from a voice channel, resulting in following attempts at connecting failing.

### Reproduction Steps

Connect your bot to a voice channel
Manually disconnect it from within the discord client
Try to reconnect it
ClientException

### Expected Results

Pycord should automatically handle any disconnections within the library by fully disconnecting the voice client. The only time that a bot should need to handle voice connections is when it wants to move to a new voice channel, connect to a voice channel, or disconnect from a voice channel. It should not need to update if it is moved/disconnected via client, or if its channel is deleted. That should be built into pycord imo (and I think most of it already is)

### Actual Results

Users have to come up with ways to detect and handle when their bots are disconnected unexpectedly, which isn't always easy/obvious

### Intents

All

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b1
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Middledot** [comment] 2022-03-20 01:11
Can you provide a code example because I can't seem to reproduce

**Comment by Dorukyum** [comment] 2022-04-17 14:52
@KosmicAnomaly can you share the minimal reproducible code and check if this is still an issue?

**Comment by Dorukyum** [comment] 2022-04-21 09:07
Fixed in #1273.

**Closed by Dorukyum** 2022-04-21 09:07 UTC
Labels: unconfirmed bug
