### ISSUE TITLE
Getting an error when I set bot's help command to commands.MinimalHelpCommand() class

### ISSUE THREAD

**Issue by ThatGenZGamer48** [Pycord-Development/pycord#337] opened 2021-10-27 07:43 UTC
### Summary

Error when setting bot's help command to commands.MinimalHelpCommand()

### Reproduction Steps

Set the bot's default help command to commands.MinimalHelpCommand() like below
```py
bot = commands.Bot(
    command_prefix="!",
    help_command=commands.MinimalHelpCommand(),
)
```

### Minimal Reproducible Code

```python
bot = commands.Bot(
	command_prefix="!",
	intents=discord.Intents(members=True, messages=True),
	status=status,
	activity=activity,
	help_command=commands.MinimalHelpCommand()
)
```

### Expected Results

I expected the help command to work as a default MinimalHelpCommand but it didnt work and when I tried the cmd it didnt say anything

### Actual Results

Ignoring exception in command help:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 173, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\help.py", line 837, in command_callback
    return await self.send_bot_help(mapping)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\help.py", line 1268, in send_bot_help
    note = self.get_opening_note()
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\help.py", line 1148, in get_opening_note
    f"Use `{self.context.clean_prefix}{command_name} [command]` for more info on a command.\n"
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\context.py", line 274, in clean_prefix
    pattern = re.compile(r"<@!?%s>" % user.id)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\bot.py", line 980, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 910, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 182, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'

Get above error and command not working

### Intents

members and messages intents

### System Information

![image](https://user-images.githubusercontent.com/78960084/139022033-4e720cab-7a24-4940-9d39-863bcb7f1712.png)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment] 2021-11-01 22:33
@ThatGenZGamer48 do you use application commands?

**Comment by ThatGenZGamer48** [comment] 2021-11-08 05:49
okay thanks!

**Comment by ThatGenZGamer48** [comment] 2021-11-08 05:50
I partly use message commands and partly application

> @ThatGenZGamer48 do you use application commands?

**Comment by Makiyu-py** [comment] 2022-01-22 16:36
Error cannot reproduce anymore.

But when having message commands with the help command, it gives this error:
```
Ignoring exception in command help:
Traceback (most recent call last):
  File "pycord/discord/ext/commands/core.py", line 179, in wrapped
    ret = await coro(*args, **kwargs)
  File "pycord/discord/ext/commands/help.py", line 838, in command_callback
    mapping = self.get_bot_mapping()
  File "pycord/discord/ext/commands/help.py", line 382, in get_bot_mapping
    mapping[None] = [c for c in bot.commands if c.cog is None]
  File "pycord/discord/ext/commands/core.py", line 1182, in commands
    return set(self.all_commands.values())
TypeError: unhashable type: 'MessageCommand'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pycord/discord/ext/commands/bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "pycord/discord/ext/commands/core.py", line 916, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "pycord/discord/ext/commands/core.py", line 188, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unhashable type: 'MessageCommand'
```
Also tested this on slash commands, gives the same error but the type being `SlashCommand` instead of the `MessageCommand` above, which means that the prefixed help commands doesn't work when there's application commands.

Not sure if this is a topic of this issue or a separate one altogether.

**Comment by plun1331** [comment] 2022-01-22 17:00
> Error cannot reproduce anymore.
> 
> But when having message commands with the help command, it gives this error:
> ```
> Ignoring exception in command help:
> Traceback (most recent call last):
>   File "pycord/discord/ext/commands/core.py", line 179, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "pycord/discord/ext/commands/help.py", line 838, in command_callback
>     mapping = self.get_bot_mapping()
>   File "pycord/discord/ext/commands/help.py", line 382, in get_bot_mapping
>     mapping[None] = [c for c in bot.commands if c.cog is None]
>   File "pycord/discord/ext/commands/core.py", line 1182, in commands
>     return set(self.all_commands.values())
> TypeError: unhashable type: 'MessageCommand'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "pycord/discord/ext/commands/bot.py", line 335, in invoke
>     await ctx.command.invoke(ctx)
>   File "pycord/discord/ext/commands/core.py", line 916, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "pycord/discord/ext/commands/core.py", line 188, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unhashable type: 'MessageCommand'
> ```
> Also tested this on slash commands, gives the same error but the type being `SlashCommand` instead of the `MessageCommand` above, which means that the prefixed help commands doesn't work when there's application commands.
> 
> Not sure if this is a topic of this issue or a separate one altogether.

This was caused by #817 which was reverted

**Comment by Makiyu-py** [comment] 2022-01-23 03:07
> > Error cannot reproduce anymore.
> > But when having message commands with the help command, it gives this error:
> > ```
> > Ignoring exception in command help:
> > Traceback (most recent call last):
> >   File "pycord/discord/ext/commands/core.py", line 179, in wrapped
> >     ret = await coro(*args, **kwargs)
> >   File "pycord/discord/ext/commands/help.py", line 838, in command_callback
> >     mapping = self.get_bot_mapping()
> >   File "pycord/discord/ext/commands/help.py", line 382, in get_bot_mapping
> >     mapping[None] = [c for c in bot.commands if c.cog is None]
> >   File "pycord/discord/ext/commands/core.py", line 1182, in commands
> >     return set(self.all_commands.values())
> > TypeError: unhashable type: 'MessageCommand'
> > 
> > The above exception was the direct cause of the following exception:
> > 
> > Traceback (most recent call last):
> >   File "pycord/discord/ext/commands/bot.py", line 335, in invoke
> >     await ctx.command.invoke(ctx)
> >   File "pycord/discord/ext/commands/core.py", line 916, in invoke
> >     await injected(*ctx.args, **ctx.kwargs)
> >   File "pycord/discord/ext/commands/core.py", line 188, in wrapped
> >     raise CommandInvokeError(exc) from exc
> > discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: unhashable type: 'MessageCommand'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also tested this on slash commands, gives the same error but the type being `SlashCommand` instead of the `MessageCommand` above, which means that the prefixed help commands doesn't work when there's application commands.
> > Not sure if this is a topic of this issue or a separate one altogether.
> 
> This was caused by #817 which was reverted

Re-tested on the latest commit, and it seems as so! Closing...

**Closed by Makiyu-py** 2022-01-23 03:07 UTC
Labels: unconfirmed bug
