### ISSUE TITLE
Defining options in SlashCommands init rases error when using the command

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#717] opened 2022-01-06 19:17 UTC
### Summary

Defining options in SlashCommands init rases error when using the command

### Reproduction Steps

1.) Create a Slash Command with options by using `options=[...]` 
2.) Use the command

### Minimal Reproducible Code

```python
command = discord.SlashCommand(
    self.callback, name='test',
    options=[discord.Option(int, name='option', description='Lorem ipsum')]
)
# challenges_commands.options[0]._parameter_name = 'option'   Workaround
bot.add_application_command(command)
```

### Expected Results

The command will be executed without any exception

### Actual Results

Following error is thrown due to the missing `_parameter_name`

### Intents

guilds, members, guild_messages, dm_messages

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4748+gc602bc45
- aiohttp v3.8.1
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This issue was apparently introduced with my pr https://github.com/Pycord-Development/pycord/pull/471. Am sorry that my testing wasn't sufficient. Unfortunately am currently busy and am not sure if I can manage to fix this.

A possible fix might be allowing the user to pass the parameter_name. Alternatively it can be set to the option name. But this could cause problems when using python incompatible names.

**Comment by plun1331** [comment] 2022-01-06 23:12
Duplicate of #555

**Closed** 2022-01-07 04:18 UTC
Labels: unconfirmed bug
