### ISSUE TITLE
Option([XX, YY]) doesn't work

### ISSUE THREAD

**Issue by MagicalBomb** [Pycord-Development/pycord#1233] opened 2022-04-08 06:46 UTC
### Summary

Option([XX, YY]) doesn't work

### Reproduction Steps

launch minimal code, it raises exception directly

### Minimal Reproducible Code

```python
import discord
from discord.commands import slash_command, Option


bot = discord.Bot()

from discord.commands import slash_command

@slash_command()
async def test(ctx, channel: Option([discord.TextChannel, discord.VoiceChannel])):
    ctx.respond("Hello")


bot.run("XXX")
```

### Expected Results

bot launch normally

### Actual Results

bot raised a exception, and program exit with error.

```Python
Traceback (most recent call last):
  File "/Users/XXX/Desktop/test.py", line 14, in <module>
    ctx.respond("Hello")
  File "/Users/XXX/Desktop/venv/lib/python3.10/site-packages/discord/commands/options.py", line 132, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "/Users/XXX/Desktop/venv/lib/python3.10/site-packages/discord/enums.py", line 653, in from_datatype
    if datatype.__name__ in ["Member", "User"]:
AttributeError: 'list' object has no attribute '__name__'. Did you mean: '__ne__'?
```

### Intents

None

### System Information

- Python v3.10.1-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b5
- aiohttp v3.7.4.post0
- system info: Darwin 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Dorukyum** [comment] 2022-04-08 17:10
Duplicate of #991.

**Closed by Dorukyum** 2022-04-08 17:10 UTC
Labels: unconfirmed bug
