### ISSUE TITLE
'SlashCommand' object has no attribute 'id'

### ISSUE THREAD

**Issue by XavierToresLopez** [Pycord-Development/pycord#389] opened 2021-11-03 19:42 UTC
### Summary

When using slash commands in cogs, this error comes up.

### Reproduction Steps

1. Using commands.Bot, not discord.Bot
2. Created a cog.
3. Made a slash command inside the cog.
4. Works fine.
5. Attempting to reload the cog throws an attribute error.

### Minimal Reproducible Code

```python
Command in server: /reload cogs.moderation

Error: Application Command raised an exception: AttributeError: 'SlashCommand' object has no attribute 'id'
```

### Expected Results

Successfully reload the cog

### Actual Results

Ignoring exception in command <discord.commands.SlashCommand name=reload>:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/commands.py", line 84, in wrapped
    ret = await coro(arg)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/commands.py", line 492, in _invoke
    await self.callback(ctx, **kwargs)
  File "main.py", line 128, in reload
    raise e
  File "main.py", line 126, in reload
    client.reload_extension(f"cogs.{extension}")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 712, in reload_extension
    self._remove_module_references(lib.__name__)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 506, in _remove_module_references
    self.remove_cog(cogname)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 490, in remove_cog
    cog._eject(self)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/cog.py", line 484, in _eject
    bot.remove_application_command(command)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 133, in remove_application_command
    return self.application_commands.pop(command.id)
AttributeError: 'SlashCommand' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/bot.py", line 382, in process_application_commands
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/commands.py", line 133, in invoke
    await injected(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/commands/commands.py", line 90, in wrapped
    raise ApplicationCommandInvokeError(exc) from exc
discord.commands.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'SlashCommand' object has no attribute 'id'

### Intents

intents = discord.Intents().all()

### System Information

- Python v3.8.12-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4310+g6008275
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-1021-gcp #23~20.04.1-Ubuntu SMP Fri Oct 1 19:04:32 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Full traceback is in the "Expected Results" Section.

**Comment by zeffo** [comment] 2021-11-03 19:54
#388 should fix this.

**Comment by krittick** [comment] 2021-11-03 19:57
Also a duplicate of #181 I believe.

**Comment by Lulalaby** [comment] 2021-11-03 20:05
Closing as dup

**Closed by Lulalaby** 2021-11-03 20:05 UTC
Labels: unconfirmed bug
