### ISSUE TITLE
Add send(file=file) feature

### ISSUE THREAD

**Issue by mcbabo** [Pycord-Development/pycord#215] opened 2021-09-18 19:15 UTC
### Summary

Add send(file=file) feature like in discord.py

### What is the feature request for?

The core library

### The Problem

`await ctx.send(file=your_file, embed=embed)`
`TypeError: send_message() got an unexpected keyword argument 'file'`

### The Ideal Solution

send files in chat

**Comment by MhmCats** [comment] 2021-09-18 19:16
Duplicate of #196

**Closed** 2021-09-18 19:17 UTC
Labels: duplicate
