### ISSUE TITLE
Allow parameter to be named different then option name

### ISSUE THREAD

**Issue by Luc1412** [Pycord-Development/pycord#373] opened 2021-11-02 13:09 UTC
### Summary

Parameters should be named differently than option names

### What is the feature request for?

The core library

### The Problem

In some cases, the parameter name can shadow a built-in function.
Here an example:
`type: discord.Option(..,)`
This would shadow the type function. 

Another example are names that would be invalid for a parameter name eg. `foo-bar`
### The Ideal Solution

Just `discord.Option.name` should define the displayed option name. The parameter can be set to any valid parameter name.
Example:
`example_type: discord.Option(..,, name='type')`

### The Current Solution

none

**Comment by nerdguyahmad** [comment] 2021-11-02 13:19
duplicate of #106

**Closed** 2021-11-02 13:25 UTC
Labels: feature request, priority: medium, status: todo

**Comment by BobDotCom** [comment] 2021-11-15 16:26
Removed from milestone and added original issue instead.
