### ISSUE TITLE
@slash_command and @user_command in cog files makes only one register and not the other

### ISSUE THREAD

**Issue by Lunar-Firefly** [Pycord-Development/pycord#1075] opened 2022-02-23 16:39 UTC
### Summary

Commenting out one or the other doesn't work either. Re-invited, Checked Intents; nothing worked.

### Reproduction Steps

1. Use Cogs
2. Use the @slash_command and @user_command decorators.

### Minimal Reproducible Code

```python
from discord import Member, Embed
from discord.commands import Option
from discord.ext import commands
from bot_utils import get_guilds


class User(commands.Cog):

    def __init__(self, client):
        self.client = client

    @commands.slash_command(name="user", description="Shows information about the user.", guild_ids=get_guilds())
    async def user(self, ctx, member: Option(Member, description="The user to show information about.", required=True)):
        information_embed = Embed(
            title=f"{member.name}#{member.discriminator} {'[Bot]' if member.bot else ''}",
            colour=member.color,
        ).set_thumbnail(
            url=member.avatar.url
        ).add_field(
            name="Created",
            value=str(member.created_at)[0:-13],
            inline=True
        ).add_field(
            name="Joined",
            value=str(member.joined_at)[0:-13],
            inline=True
        ).set_footer(
            text=member.id
        )
        await ctx.respond(embeds=[information_embed])

    @commands.user_command(name="Account Information", description="Shows information about this user.", guild_ids=get_guilds())
    async def user(self, ctx, member: Member):
        information_embed = Embed(
            title=f"{member.name}#{member.discriminator} {'[Bot]' if member.bot else ''}",
            colour=member.color,
        ).set_thumbnail(
            url=member.avatar.url
        ).add_field(
            name="Created",
            value=str(member.created_at)[0:-13],
            inline=True
        ).add_field(
            name="Joined",
            value=str(member.joined_at)[0:-13],
            inline=True
        ).set_footer(
            text=str(member.id)
        )
        await ctx.respond(embeds=[information_embed], ephemeral=True)


def setup(client):
    client.add_cog(User(client))
```

### Expected Results

/user to show up in preview and work alongside context menus

### Actual Results

Only context menus work and not the slash commands

### Intents

all()

### System Information

- Python v3.10.2-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.8.1
- system info: Linux 5.13.15-1-MANJARO #1 SMP PREEMPT Wed Sep 8 14:12:50 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by krittick** [comment] 2022-02-23 22:03
Duplicate of #954

**Closed by krittick** 2022-02-23 22:03 UTC
Labels: unconfirmed bug

**Comment by plun1331** [comment] 2022-02-24 02:01
Don't name both command callbacks the same thing or one will override the other.
