### ISSUE TITLE
Slash Command Registration

### ISSUE THREAD

**Issue by SquitchYT** [Pycord-Development/pycord#847] opened 2022-01-24 18:36 UTC
### Summary

Slash Command Registration doesn't work if "text command" already registered with the same name

### Reproduction Steps

* Create a simple ping `text command`
* Create a simple ping `slash command`
* The slash command was not registered

### Minimal Reproducible Code

```python
@commands.slash_command(guild_ids=[...])
async def ping(self, ctx) -> None:
        ...


@commands.command()
async def ping(self, ctx) -> None:
        ...
```

### Expected Results

Slash command would be registered

### Actual Results

Slash command is not registered

### Intents

ALL

### System Information

- Python v3.10.0-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4748+gc602bc45
- aiohttp v3.8.1
- system info: Linux 5.11.22-2-pve #1 SMP PVE 5.11.22-3 (Sun, 11 Jul 2021 13:45:15 +0200)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment] 2022-01-24 18:44
![image](https://user-images.githubusercontent.com/14029133/150844571-1de9be68-a779-4f09-b383-f468ffe521bc.png)
Use the latest version

**Comment by zeffo** [comment] 2022-01-25 16:48
Could you elaborate a bit more? Cannot reproduce this with the provided code.

**Comment by SquitchYT** [comment] 2022-01-25 17:26
I want to make a "normal" version and a slash command version of my commands. I'm in cog.
Here a sample of the script 
```
    @commands.slash_command(guild_ids=[...])
    async def purge(self, ctx, count: Option(int, "Number of messages to delete", required=False, default=25), channel: Option(str, "test", required=False)) -> None:
        ...

    @commands.command(aliases=["clear"])
    async def purge(self, ctx: Context, count: int=25):
       ...
```

Unfortunately, only the "normal" command is registered. If I change the name of the slash command to something else (like `foo`), the slash command is registered too. And if I change the name of the "normal" command to `foo`, only the "normal" command is registered

**Comment by Makiyu-py** [comment] 2022-01-26 07:48
Cannot reproduce, at least on my system.

There's no such thing as a `slash_command` decorator on `discord.ext.commands`.

If `commands` is actually `discord.commands`, then almost the same thing but switched.
The `discord.commands.command` decorator is simply, as stated in the docs, an alias for the `application_command` decorator.

**Comment by krittick** [comment] 2022-01-26 16:27
> There's no such thing as a `slash_command` decorator on `discord.ext.commands`.

This is not correct. See here: https://github.com/Pycord-Development/pycord/blob/eb981d3132e224cf3e22db98e7eb62cca5b8d243/discord/ext/commands/core.py#L56-L62


I'm also able to reproduce this bug with the following code, even when using `from discord.commands import slash_command`:

```py
@slash_command(name="nametest_slash" guild_ids=[...])
async def nametest(self, ctx):
    await ctx.respond("command name test slash")

@commands.command()
async def nametest(self, ctx):
    await ctx.send("command name test prefix")
```

In this situation, only the prefix command is registered. The slash command does not appear at all despite having a different name defined in the decorator. Renaming the function (not the `name` parameter) to something else causes it to show up.

If you reverse the order of the commands in the code, then only the slash command is registered and the prefix command is not:

```py
@commands.command()
async def nametest(self, ctx):
    await ctx.send("command name test prefix")

@slash_command(name="nametest_slash" guild_ids=[...])
async def nametest(self, ctx):
    await ctx.respond("command name test slash")
```

**Comment by Lulalaby** [comment] 2022-01-26 16:41
how can it be fixed

**Comment by AnimateShadows** [comment] 2022-01-26 20:41
I think that I know what is going on here and I have written this test code to (sort of) prove that:
```py
class Wrapper:
    def __init__(self, name, callback):
        self.name = name
        self.callback = callback

    def __del__(self):
        print("deleting ", self.name, "...", sep="")

def wraps(name):
    def deco(func):
        obj = Wrapper(name=name, callback=func)
        return obj
    return deco

@wraps(name="test1")
def test():
    ...

print("registered test1")

@wraps(name="test2")
def test():
    ...

print("registered test2")

```

The outcome is that the program starts, test1's `__del__` method is called when test2 is registered, giving us the following output:
```
$ python3 test.py
registered test1
deleting test1...
registered test2
deleting test2...
```
test2 is also deleted because at this point, the program exists.

I would not expect redefining a variable to work like you seem to think it should unless you do some strange things with `__del__` (please don't). A better solution would to just be to call the functions different things, there is a `name` kwarg in both decorators!

**Comment by krittick** [comment] 2022-01-26 20:50
Looking at this again with the context of the above comment, I'm inclined to agree that this isn't a bug as well. I had originally thought this was (re)introduced as an issue, but it appears to have been a thing ever since discord.py and prefix commands.

Just name your functions differently (e.g. slash_name, prefix_name) and this isn't an issue. I'll be closing this now but feel free to re-open if further evidence points this to being an actual bug.

**Closed by krittick** 2022-01-26 20:50 UTC
Labels: bug
