### ISSUE TITLE
`SlashCommandOptionType.user` doesn't work

### ISSUE THREAD

**Issue by HeroClay** [Pycord-Development/pycord#1120] opened 2022-03-05 20:10 UTC
### Summary

`SlashCommandOptionType.user` doesn't work

### Reproduction Steps

I tried to make a slash command containing the `SlashCommandOptionType.user` type, and there it started making trouble. I've tried `Option(pycord.Member)` too, with exact the same result.

### Minimal Reproducible Code

```python
@bot.slash_command(name="kick", guild_ids=[...])
async def command(ctx, member: pycord.SlashCommandOptionType.user):
    pass
```

### Expected Results

The bot starts

### Actual Results

Traceback (most recent call last):
  File "/var/global/justmorebot/main.py", line 383, in <module>
    async def kick_user_command(interaction: pycord.Interaction, member: pycord.SlashCommandOptionType.user):
  File "/home/heroclay/.local/lib/python3.8/site-packages/discord/bot.py", line 822, in decorator
    result = command(**kwargs)(func)
  File "/home/heroclay/.local/lib/python3.8/site-packages/discord/commands/core.py", line 1457, in decorator
    return cls(func, **attrs)
  File "/home/heroclay/.local/lib/python3.8/site-packages/discord/commands/core.py", line 590, in __init__
    self.options: List[Option] = self._parse_options(params)
  File "/home/heroclay/.local/lib/python3.8/site-packages/discord/commands/core.py", line 638, in _parse_options
    option = Option(option, "No description provided")
  File "/home/heroclay/.local/lib/python3.8/site-packages/discord/commands/options.py", line 124, in __init__
    _type = SlashCommandOptionType.from_datatype(input_type)
  File "/home/heroclay/.local/lib/python3.8/site-packages/discord/enums.py", line 654, in from_datatype
    if datatype.__name__ in ["Member", "User"]:
AttributeError: 'str' object has no attribute '__name__'

### Intents

guild_reactions, messages, bans, guilds

### System Information

- Python v3.8.10-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b4
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0 `#1` SMP Thu Apr 22 16:18:59 MSK 2021

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by EmreTech** [comment] 2022-03-05 20:17
Sounds like a problem that will be fixed with #863.

**Comment by HeroClay** [comment] 2022-03-05 20:18
Ok thanks!

**Comment by Dorukyum** [comment] 2022-03-05 20:21
We shouldn't close issues until they are solved to be able to track them.

**Comment by Dorukyum** [comment] 2022-03-06 09:42
I can't reproduce this with beta 4.

**Closed** 2022-04-09 18:57 UTC
Labels: unconfirmed bug
