### ISSUE TITLE
discord.Message typehint

### ISSUE THREAD

**Issue by RayyanW786** [Pycord-Development/pycord#801] opened 2022-01-15 18:06 UTC
### Summary

seems like whenever you typehint a argument to discord.Message and the user puts a message id as the argument i always get this error however message reference and message link work

### Reproduction Steps

<img width="418" alt="image" src="https://user-images.githubusercontent.com/97803050/149632577-bfe76b29-b229-45be-8009-3c779aa017b4.png">
<img width="541" alt="image" src="https://user-images.githubusercontent.com/97803050/149632607-ac5b3104-716c-4754-b19a-ed16cd5eb854.png">

as you see message reference works fine aswell as message links  however when i tried to use message ids it didnt work due to the following error
```py
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 908, in invoke
    await self.prepare(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 838, in prepare
    await self._parse_arguments(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 744, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 596, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 1183, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 1077, in _actual_conversion
    return await converter().convert(ctx, argument)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 396, in convert
    raise ChannelNotFound(channel_id)
discord.ext.commands.errors.ChannelNotFound: Channel "None" not found
```

### Minimal Reproducible Code

```py
@bot.command(help = "a simple command", hidden = False, usage = "<message>")
async def test_cmd(ctx, message: discord.Message):
    chan = await bot.fetch_channel(message.channel.id) #this line errors out.
    await message.reply("hi this is a reply!")
```

### Expected Results

when the user would run prefix test_cmd(message_id_here), the bot would reply to the message provided with "hi this is a reply"

### Actual Results

what happens is the following error is raised and the bot doesnt reply to the message

```py
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 335, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 908, in invoke
    await self.prepare(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 838, in prepare
    await self._parse_arguments(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 744, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 596, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 1183, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 1077, in _actual_conversion
    return await converter().convert(ctx, argument)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/converter.py", line 396, in convert
    raise ChannelNotFound(channel_id)
discord.ext.commands.errors.ChannelNotFound: Channel "None" not found
```

### Intents

all

### System Information

```
- Python v3.8.12-final
- py-cord v2.0.0-alpha
    - py-cord pkg_resources: v2.0.0a4795+g71c0711e
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-1024-gcp #26~20.04.1-Ubuntu SMP Wed Dec 8 10:29:18 UTC 2021
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Lulalaby** [comment] 2022-01-15 18:10
@Pycord-Development/official-contributors

**Comment by Kawaritai** [comment] 2022-01-16 01:51
Hey, I've been investigating this issue. 
Inside the `MessageConverter` class within discord\ext\commands\converter.py , line 391, a change of
```python
message = ctx.bot._connection._get_message(message_id)
```
to ->

```python
message = await ctx.fetch_message(message_id)
```
successfully returns a discord Message, thus allowing message id to be used as the command argument. It also obeys the docstring lookup strategy, 
"2. Lookup by message ID (the message **must** be in the context channel)"
Message link arguments work as desired (including links to messages outside the context channel), but message id's won't work if referencing outside the context channel. Perhaps there is some method to resolve this?

This change uses a coroutine function with `await` -- I'm not aware on how this could affect/break other features. 

(new to github things btw, help is appreciated 😄)

**Comment by Makiyu-py** [comment] 2022-01-16 13:44
This seems to be an old problem stemming back to September, with #185.
But I can't say whether if this is a duplicate of that issue or not, due to the age of the said issue.

**Comment by RayyanW786** [comment] 2022-01-16 20:12
> 

Oops my bad I was told that there wasn’t any other duplicates

**Closed** 2022-01-19 06:34 UTC
Labels: bug, good first issue, priority: medium, status: todo
