### ISSUE TITLE
discord-ext-ipc not working with pycord

### ISSUE THREAD

**Issue by Rishabh4Jakhar** [Pycord-Development/pycord#626] opened 2021-12-23 15:28 UTC
### Summary

So hmm while trying to use `discord-ext-ipc` with pycord there seems to be a issue. So what you would do normally is just do `bot.ipc.start()` at the end of the code to start the ipc server. But while doing so in pycord it raises this [error](https://mystb.in/GuiltyComePvc.sql) It is due to some async issue in the files.  

### Reproduction Steps

I was basically following this [code](https://github.com/CodeWithSwastik/Dashboard-Tutorials/blob/main/Part%203/bot.py) from one of your developers. This should pretty much get you the same error.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands, ipc

TOKEN = ""

class MyBot(commands.Bot):

	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)

		self.ipc = ipc.Server(self,secret_key = "Swas")

	async def on_ready(self):
		"""Called upon the READY event"""
		print("Bot is ready.")

	async def on_ipc_ready(self):
		"""Called upon the IPC Server being ready"""
		print("Ipc server is ready.")

	async def on_ipc_error(self, endpoint, error):
		"""Called upon an error being raised within an IPC route"""
		print(endpoint, "raised", error)


my_bot = MyBot(command_prefix = ">", intents = discord.Intents.default())


@my_bot.ipc.route()
async def get_guild_count(data):
	return len(my_bot.guilds) # returns the len of the guilds to the client

@my_bot.ipc.route()
async def get_guild_ids(data):
	final = []
	for guild in my_bot.guilds:
		final.append(guild.id)
	return final # returns the guild ids to the client

@my_bot.ipc.route()
async def get_guild(data):
	guild = my_bot.get_guild(data.guild_id)
	if guild is None: return None

	guild_data = {
		"name": guild.name,
		"id": guild.id,
		"prefix" : "?"
	}

	return guild_data

@my_bot.command()
async def hi(ctx):
	await ctx.send("Hi")

my_bot.ipc.start()
my_bot.run(TOKEN)
```

### Expected Results

I expected it to normally start the ipc server as it does but as seen in the error linked above it doesn't.

### Actual Results

It sends a client._run_event was never awaited issue.

### Intents

Default intents

### System Information

well the command runs some error but anyways
`Operating system - Windows 10`
`RAM - 8 GB`
`64 Bit`
`Python - 3.9.x`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by HyperGH** [comment] 2021-12-23 15:33
The issue is caused by `on_ipc_ready()` and is also triggered in discord.py 2.0, this is a bug with `ext.ipc`, not pycord

**Comment by HyperGH** [comment] 2021-12-23 15:34
See this issue: https://github.com/Ext-Creators/discord-ext-ipc/issues/47

**Comment by Lulalaby** [comment] 2021-12-23 15:35
Closing as invalid

**Closed by Lulalaby** 2021-12-23 15:35 UTC
Labels: invalid

**Comment by Rishabh4Jakhar** [comment] 2021-12-24 06:14
hmm so there is no way I can use both pycord and ipc ? since ipc's development is closed now I don't expect that the bug will be fixed on their end. But using `buttons` and `slash commands` among other things is important for my bot.
Any chances of you forking ipc repo and making your own `ext-ipc` compatible with pycord. It would me much appreciated. Even a workaround would do it for me.
Thanks

**Comment by VincentRPS** [comment] 2021-12-24 06:17
> hmm so there is no way I can use both pycord and ipc ? since ipc's development is closed now I don't expect that the bug will be fixed on their end. But using `buttons` and `slash commands` among other things is important for my bot. Any chances of you forking ipc repo and making your own `ext-ipc` compatible with pycord. It would me much appreciated. Even a workaround would do it for me. Thanks

well i am making a official ext based off it for pycord but while that is being develop maybe make an issue on [pycord-ext-ipc](https://github.com/xFGhoul/pycord-ext-ipc)

**Comment by krittick** [comment] 2021-12-24 06:30
> ```python
> 	async def on_ipc_ready(self):
> ```

The workaround is to remove `on_ipc_ready` from your code and it will function just fine without that event handler. I do that myself and it works great for my bot, which can route thousands of requests a minute.

**Comment by krittick** [comment] 2021-12-24 06:30
> hmm so there is no way I can use both pycord and ipc ? since ipc's development is closed now I don't expect that the bug will be fixed on their end. But using `buttons` and `slash commands` among other things is important for my bot. Any chances of you forking ipc repo and making your own `ext-ipc` compatible with pycord. It would me much appreciated. Even a workaround would do it for me. Thanks

The workaround is to remove `on_ipc_ready` from your code and it will function just fine without that event handler. I do that myself and it works great for my bot, which can route thousands of requests a minute.

**Comment by Rishabh4Jakhar** [comment] 2021-12-28 06:18
Sorry for the late reply wasn't at home, thanks for the workaround @krittick 
And I am looking forward to the the ext 👍
