### ISSUE TITLE
Message Command Error

### ISSUE THREAD

**Issue by challos** [Pycord-Development/pycord#915] opened 2022-02-04 04:46 UTC
### Summary

Bot has issue with the message command decorator

### Reproduction Steps

I run the minimal code.

### Minimal Reproducible Code

```python
#!/usr/bin/env python3

import discord
from discord.ext import commands
from discord.commands import Option

guilds = [<guild id here>]


bot = commands.Bot()


@bot.slash_command(
    name="upload_to_imgur",
)
async def upload_to_imgur(
    ctx: discord.ApplicationContext,
    raw_link: Option(str, "File to be uploaded.", name="image_link", default=""),
    limit: Option(
        int, description="How many messages to go back.", default=8
    ),
    only_you: Option(
        bool, "Only checks messages sent by you, true/false.", default=False
    ),
):
    pass


@bot.message_command(
    name="Upload image",
    guild_ids=guilds,
)
async def imgur_message_upload(
    ctx: discord.ApplicationContext, message: discord.Message
):
    pass


discord_token = "<discord bot token>"
bot.run(discord_token)
```

### Expected Results

I expect there to be no error when starting the bot.

### Actual Results

I got this error upon running the minimal code:

`Ignoring exception in on_connect
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.9/site-packages/discord/client.py", line 352, in _run_event
    await coro(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/discord/bot.py", line 1038, in on_connect
    await self.sync_commands()
  File "/home/pi/.local/lib/python3.9/site-packages/discord/bot.py", line 552, in sync_commands
    registered_guild_commands[guild_id] = await self.register_commands(
  File "/home/pi/.local/lib/python3.9/site-packages/discord/bot.py", line 419, in register_commands
    desynced = await self.get_desynced_commands(guild_id=guild_id)
  File "/home/pi/.local/lib/python3.9/site-packages/discord/bot.py", line 285, in get_desynced_commands
    cmd_vals = [val.get(opt, MISSING) for val in as_dict[check]]
KeyError: 'options'`

### Intents

130813

### System Information

- Python v3.9.5-final
- py-cord v2.0.0-beta
    - py-cord pkg_resources: v2.0.0b3
- aiohttp v3.7.4.post0
- system info: Linux 5.10.63-v7+ #1496 SMP Wed Dec 1 15:58:11 GMT 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I wasn't able to reduce the minimum code down because whenever I tried to cut down code, it would sort of randomly throw errors, I think because there's some cache for commands somewhere? I'm sure the minimum code could be even smaller, but I think it requires both a message command and a slash command, with guild_ids.

**Comment by BobDotCom** [comment] 2022-02-04 05:26
Duplicate of #912

**Closed by BobDotCom** 2022-02-04 05:26 UTC
Labels: unconfirmed bug
